theme: minima
title: Yeah, my first page!
author: Weixuan Liu
email: liuwx2019@mail.sustech.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  Actually, I have no idea to put any text here.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  liuwx1997 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
